export {default as About} from './About/About'
export {default as Education} from './Education/Education'
export {default as Footer} from './Footer/Footer'
export{default as Navbar} from './Navbar/Navbar'
export{default as Landing} from './Landing/Landing'
export{default as Contacts} from './Contacts/Contacts'
export {default as Skills} from './Skills/Skills'
export {default as Experience} from './Experience/Experience'
export {default as Achievement} from './Achievement/Achievement'
export {default as Projects} from './Projects/Projects'
export {default as BackToTop} from './BackToTop/BackToTop'